const cartas = [
  {
    "frase": "Ella durmió al calor de las masas y yo desperté ____",
    "a": "queriendo soñarla",
    "b": "queriendo besarla",
    "c": "queriendo olvidarla",
    "respuesta": "a",
    "tema_a": "Persiana Americana",
    "tema_b": "En La Ciudad De La Furia",
    "tema_c": "De Música Ligera",
    "opcion_tema": "c",
    "banda_a": "Soda Stereo",
    "banda_b": "Gustavo Cerati",
    "banda_c": "Los Rodríguez",
    "opcion_banda": "a",
    "anio_a": "1990",
    "anio_b": "1995",
    "anio_c": "1988",
    "opcion_anio": "a"
  },
  {
    "frase": "En este film velado en blanca noche, __ ____ _____ de tu enemigo",
    "a": "el hijo tenaz",
    "b": "se fue al sur",
    "c": "es un cartel",
    "respuesta": "a",
    "tema_a": "Ji Ji Ji",
    "tema_b": "Motorpsico",
    "tema_c": "Esa estrella era mi lujo",
    "opcion_tema": "a",
    "banda_a": "La Renga",
    "banda_b": "Los Redondos",
    "banda_c": "Patricio Rey y sus Redonditos de Ricota",
    "opcion_banda": "c",
    "anio_a": "1989",
    "anio_b": "1991",
    "anio_c": "1986",
    "opcion_anio": "c"
  },
  {
    "frase": "Los amigos del barrio pueden desaparecer, pero los ____ ____",
    "a": "dinosaurios volverán un día",
    "b": "dinosaurios se van a quedar",
    "c": "dinosaurios van a desaparecer",
    "respuesta": "c",
    "tema_a": "Demoliendo Hoteles",
    "tema_b": "Los Dinosaurios",
    "tema_c": "Seminare",
    "opcion_tema": "b",
    "banda_a": "Sui Generis",
    "banda_b": "Serú Girán",
    "banda_c": "Charly García",
    "opcion_banda": "c",
    "anio_a": "1978",
    "anio_b": "1980",
    "anio_c": "1983",
    "opcion_anio": "c"
  },
  {
    "frase": "A ella le gusta la gasolina (____)",
    "a": "qué le den gasolina",
    "b": "dame más gasolina",
    "c": "como le encanta la gasolina",
    "respuesta": "b",
    "tema_a": "Lo Que Pasó, Pasó",
    "tema_b": "Gasolina",
    "tema_c": "Pobre Diabla",
    "opcion_tema": "b",
    "banda_a": "Don Omar",
    "banda_b": "Wisin & Yandel",
    "banda_c": "Daddy Yankee",
    "opcion_banda": "c",
    "anio_a": "2003",
    "anio_b": "2005",
    "anio_c": "2004",
    "opcion_anio": "c"
  },
  {
    "frase": "Me puse la' Gucci con un short de Nike, buzo y cadena, ____",
    "a": "estoy que goteo",
    "b": "me siento violento",
    "c": "estoy que exploto",
    "respuesta": "a",
    "tema_a": "Rockstar",
    "tema_b": "She Don't Give a FO",
    "tema_c": "Goteo",
    "opcion_tema": "c",
    "banda_a": "Khea & Duki",
    "banda_b": "Duki & C.R.O",
    "banda_c": "Duki",
    "opcion_banda": "c",
    "anio_a": "2020",
    "anio_b": "2019",
    "anio_c": "2018",
    "opcion_anio": "b"
  },
  {
    "frase": "Ya no ____, no quiero lastimarme de vuelta",
    "a": "vuelvas",
    "b": "llames",
    "c": "busques",
    "respuesta": "a",
    "tema_a": "Ya No Vuelvas",
    "tema_b": "Un Finde",
    "tema_c": "Pobre Corazón",
    "opcion_tema": "a",
    "banda_a": "Big One & Ke Personajes",
    "banda_b": "La K'onga, Luck Ra & Ke Personajes",
    "banda_c": "Ivy Queen",
    "opcion_banda": "b",
    "anio_a": "2004",
    "anio_b": "2023",
    "anio_c": "2023",
    "opcion_anio": "c"
  },
  {
    "frase": "Hay una ____ sola, se está moviendo, quiere un cuartetazo violento",
    "a": "rubia",
    "b": "morocha",
    "c": "pelirroja",
    "respuesta": "b",
    "tema_a": "La Rubia",
    "tema_b": "La Pelirroja",
    "tema_c": "La Morocha",
    "opcion_tema": "c",
    "banda_a": "Luck Ra ft. BM",
    "banda_b": "La Mona Jiménez",
    "banda_c": "Dalila",
    "opcion_banda": "a",
    "anio_a": "2008",
    "anio_b": "2024",
    "anio_c": "2005",
    "opcion_anio": "b"
  },
  {
    "frase": "Tírame una ____ que se vea, en la nave mientra' hacemos cosa' feas",
    "a": "foto",
    "b": "mirada",
    "c": "selfie",
    "respuesta": "a",
    "tema_a": "Sin Pijama",
    "tema_b": "Además de Mí",
    "tema_c": "Una Foto Remix",
    "opcion_tema": "c",
    "banda_a": "Mesita, Emilia, Nicki Nicole & Tiago PZK",
    "banda_b": "Rauw & Nicki",
    "banda_c": "Becky G & Natti Natasha",
    "opcion_banda": "a",
    "anio_a": "2023",
    "anio_b": "2021",
    "anio_c": "2018",
    "opcion_anio": "a"
  },
  {
    "frase": "Pero cuando se apaga la ____ se siente bien portarse mal",
    "a": "música",
    "b": "luz",
    "c": "TV",
    "respuesta": "c",
    "tema_a": "La_Original.mp3",
    "tema_b": "Jet Lag",
    "tema_c": "Mi Cuarto",
    "opcion_tema": "a",
    "banda_a": "Emilia & Duki",
    "banda_b": "Tini",
    "banda_c": "Emilia ft. Tini",
    "opcion_banda": "c",
    "anio_a": "2023",
    "anio_b": "2022",
    "anio_c": "2024",
    "opcion_anio": "c"
  },
  {
    "frase": "Mi mujer me estaba llamando, pero yo no ____",
    "a": "miré",
    "b": "escuché",
    "c": "contesté",
    "respuesta": "c",
    "tema_a": "China",
    "tema_b": "Te Boté",
    "tema_c": "Con Calma",
    "opcion_tema": "a",
    "banda_a": "Casper, Nio García, Darell",
    "banda_b": "Daddy Yankee",
    "banda_c": "Anuel AA, Daddy Yankee, Karol G, Ozuna & J Balvin",
    "opcion_banda": "c",
    "anio_a": "2019",
    "anio_b": "2018",
    "anio_c": "2019",
    "opcion_anio": "a"
  },
  {
    "frase": "Antes tú me pichaba', ahora yo ____",
    "a": "picheo",
    "b": "te picho",
    "c": "me pichas",
    "respuesta": "a",
    "tema_a": "Safaera",
    "tema_b": "Yo Perreo Sola",
    "tema_c": "Callaita",
    "opcion_tema": "b",
    "banda_a": "Bad Bunny",
    "banda_b": "J Balvin",
    "banda_c": "Bad Bunny ft. Jowell & Randy",
    "opcion_banda": "a",
    "anio_a": "2020",
    "anio_b": "2019",
    "anio_c": "2020",
    "opcion_anio": "c"
  },
  {
    "frase": "Llegué al club con el combo, rápido la vi ____",
    "a": "cerca",
    "b": "lejos",
    "c": "bailando",
    "respuesta": "b",
    "tema_a": "Nos fuimos en Una",
    "tema_b": "Quevedo: Bzrp Music Sessions #52",
    "tema_c": "Un x100to",
    "opcion_tema": "b",
    "banda_a": "Feid & Bizarrap",
    "banda_b": "Grupo Frontera & Bad Bunny",
    "banda_c": "Bizarrap & Quevedo",
    "opcion_banda": "c",
    "anio_a": "2023",
    "anio_b": "2022",
    "anio_c": "2025",
    "opcion_anio": "b"
  },
  {
    "frase": "Hola ____, soy yo el ex amor de tu vida",
    "a": "loca",
    "b": "perdida",
    "c": "mentirosa",
    "respuesta": "b",
    "tema_a": "Hola Remix",
    "tema_b": "Hola Perdida",
    "tema_c": "Ya Me Enteré",
    "opcion_tema": "b",
    "banda_a": "Reik ft. Ozuna",
    "banda_b": "Luck Ra & Tini",
    "banda_c": "Luck Ra ft. Khea",
    "opcion_banda": "c",
    "anio_a": "2024",
    "anio_b": "2016",
    "anio_c": "2023",
    "opcion_anio": "a"
  },
  {
    "frase": "Éramos tan buenos amigos ____, que yo probé tu desempeño en el amor",
    "a": "hasta hoy",
    "b": "ayer",
    "c": "desde siempre",
    "respuesta": "a",
    "tema_a": "Perfecta",
    "tema_b": "Don",
    "tema_c": "Yo No Sé",
    "opcion_tema": "a",
    "banda_a": "Bandana",
    "banda_b": "Julieta Venegas",
    "banda_c": "Miranda!",
    "opcion_banda": "c",
    "anio_a": "2005",
    "anio_b": "2002",
    "anio_c": "2007",
    "opcion_anio": "c"
  },
  {
    "frase": "Todas las mañanas que viví, todas las calles donde me ____",
    "a": "escondí",
    "b": "perdí",
    "c": "encontré",
    "respuesta": "a",
    "tema_a": "11 y 6",
    "tema_b": "Mariposa Tecknicolor",
    "tema_c": "Al Lado del Camino",
    "opcion_tema": "b",
    "banda_a": "Fito Páez",
    "banda_b": "Los Auténticos Decadentes",
    "banda_c": "La Renga",
    "opcion_banda": "a",
    "anio_a": "1998",
    "anio_b": "1990",
    "anio_c": "1994",
    "opcion_anio": "c"
  },
  {
    "frase": "Despacito, quiero respirar tu cuello ____",
    "a": "despacito",
    "b": "lentamente",
    "c": "suavemente",
    "respuesta": "a",
    "tema_a": "Despacito",
    "tema_b": "Felices los 4",
    "tema_c": "Échame La Culpa",
    "opcion_tema": "a",
    "banda_a": "Luis Fonsi ft. Daddy Yankee",
    "banda_b": "Luis Fonsi & Demi Lovato",
    "banda_c": "Maluma",
    "opcion_banda": "a",
    "anio_a": "2019",
    "anio_b": "2018",
    "anio_c": "2017",
    "opcion_anio": "c"
  },
  {
    "frase": "Con calma, yo quiero ver cómo ella lo ____",
    "a": "baila",
    "b": "menea",
    "c": "mueve",
    "respuesta": "b",
    "tema_a": "Dura",
    "tema_b": "Con Calma",
    "tema_c": "Tusa",
    "opcion_tema": "b",
    "banda_a": "Daddy Yankee ft. Snow",
    "banda_b": "Daddy Yankee",
    "banda_c": "Karol G & Nicki Minaj",
    "opcion_banda": "a",
    "anio_a": "2019",
    "anio_b": "2019",
    "anio_c": "2018",
    "opcion_anio": "a"
  },
  {
    "frase": "Y yo le di un ____ en la boca, pa' cada loco su loca",
    "a": "besito",
    "b": "mordisco",
    "c": "cachetazo",
    "respuesta": "a",
    "tema_a": "Mujeriego",
    "tema_b": "Loca",
    "tema_c": "¿Y Pa' La Wacha Loca? Remix",
    "opcion_tema": "c",
    "banda_a": "Gusty DJ, La Joaqui, L-Gante & Salastkbron",
    "banda_b": "La Joaqui",
    "banda_c": "Damas Gratis",
    "opcion_banda": "a",
    "anio_a": "2023",
    "anio_b": "2008",
    "anio_c": "2021",
    "opcion_anio": "a"
  },
  {
    "frase": "Te prefiero ____, inalcanzable",
    "a": "en mis sueños",
    "b": "lejos de mí",
    "c": "fuera de foco",
    "respuesta": "c",
    "tema_a": "Persiana Americana",
    "tema_b": "Signos",
    "tema_c": "Nada Personal",
    "opcion_tema": "a",
    "banda_a": "Gustavo Cerati",
    "banda_b": "Soda Stereo",
    "banda_c": "Bersuit",
    "opcion_banda": "b",
    "anio_a": "1985",
    "anio_b": "1986",
    "anio_c": "1986",
    "opcion_anio": "c"
  },
  {
    "frase": "Yo caminaré entre las piedras hasta sentir el ____",
    "a": "temblor, en mis piernas",
    "b": "frío de la noche",
    "c": "calor del sol",
    "respuesta": "a",
    "tema_a": "Cuando Pase el Temblor",
    "tema_b": "En El Séptimo Día",
    "tema_c": "Prófugos",
    "opcion_tema": "a",
    "banda_a": "Soda Stereo",
    "banda_b": "La Renga",
    "banda_c": "Andrés Calamaro",
    "opcion_banda": "a",
    "anio_a": "1986",
    "anio_b": "1986",
    "anio_c": "1985",
    "opcion_anio": "c"
  },
  {
    "frase": "Y que me ____ todo y no tenga nada",
    "a": "quite",
    "b": "falte",
    "c": "sobre",
    "respuesta": "b",
    "tema_a": "Ya No Vuelvas",
    "tema_b": "Que Me Falte Todo",
    "tema_c": "Hola Perdida",
    "opcion_tema": "b",
    "banda_a": "Luck Ra ft. Khea",
    "banda_b": "La K'onga & Luck Ra",
    "banda_c": "Luck Ra ft. Abel Pintos",
    "opcion_banda": "c",
    "anio_a": "2024",
    "anio_b": "2024",
    "anio_c": "2023",
    "opcion_anio": "a"
  },
  {
    "frase": "Las flores que te regalé ya se ____",
    "a": "secaron",
    "b": "marchitaron",
    "c": "cayeron",
    "respuesta": "b",
    "tema_a": "Un Finde",
    "tema_b": "Ya No Vuelvas",
    "tema_c": "Pobre Corazón",
    "opcion_tema": "a",
    "banda_a": "Big One, FMK & Ke Personajes",
    "banda_b": "La K'onga & Luck Ra",
    "banda_c": "Ke Personajes",
    "opcion_banda": "a",
    "anio_a": "2023",
    "anio_b": "2023",
    "anio_c": "2023",
    "opcion_anio": "b"
  },
  {
    "frase": "Diablo, qué ____, tú tiene' un culo cabrón",
    "a": "bellaquera",
    "b": "locura",
    "c": "safaera",
    "respuesta": "c",
    "tema_a": "Dákiti",
    "tema_b": "Yo Perreo Sola",
    "tema_c": "Safaera",
    "opcion_tema": "c",
    "banda_a": "Bad Bunny ft. Jowell & Randy y Ñengo Flow",
    "banda_b": "Bad Bunny",
    "banda_c": "Bad Bunny & Jhay Cortez",
    "opcion_banda": "a",
    "anio_a": "2018",
    "anio_b": "2020",
    "anio_c": "2021",
    "opcion_anio": "b"
  },
  {
    "frase": "Me despierto, 6:00 a.m. __ ____ ______ un domingo",
    "a": "en otro lugar",
    "b": "en otra pieza",
    "c": "en otro barrio",
    "respuesta": "c",
    "tema_a": "La Noche de Anoche",
    "tema_b": "Dákiti",
    "tema_c": "Mamichula",
    "opcion_tema": "c",
    "banda_a": "Trueno ft. Nicki Nicole & Bizarrap",
    "banda_b": "Bad Bunny & Rosalía",
    "banda_c": "Bad Bunny & Jhay Cortez",
    "opcion_banda": "a",
    "anio_a": "2020",
    "anio_b": "2020",
    "anio_c": "2021",
    "opcion_anio": "a"
  },
  {
    "frase": "Vámonos ____ de aquí, ay papi dime que sí",
    "a": "solos",
    "b": "juntos",
    "c": "lejos",
    "respuesta": "c",
    "tema_a": "La Curiosidad",
    "tema_b": "El Amor de Mi Vida",
    "tema_c": "Otra Noche en Miami",
    "opcion_tema": "b",
    "banda_a": "Bad Bunny",
    "banda_b": "Jay Wheeler & Myke Towers",
    "banda_c": "Los Ángeles Azules ft. Maria Becerra",
    "opcion_banda": "c",
    "anio_a": "2021",
    "anio_b": "2020",
    "anio_c": "2024",
    "opcion_anio": "c"
  },
  {
    "frase": "Y ahora todo está ____, antes cuando te quería tú no me querías ver",
    "a": "al revés",
    "b": "de cabeza",
    "c": "al derecho",
    "respuesta": "a",
    "tema_a": "Mala Mía",
    "tema_b": "Nena",
    "tema_c": "Al Revés",
    "opcion_tema": "c",
    "banda_a": "Cazzu",
    "banda_b": "Angela Torres",
    "banda_c": "Emilia Mernes",
    "opcion_banda": "a",
    "anio_a": "2018",
    "anio_b": "2020",
    "anio_c": "2019",
    "opcion_anio": "c"
  },
  {
    "frase": "Que milagro tiene que pasar ____",
    "a": "para que me ames",
    "b": "para que me mires",
    "c": "para que me cargues",
    "respuesta": "a",
    "tema_a": "Esclavo de tus besos",
    "tema_b": "Tu mirada",
    "tema_c": "Mi princesa",
    "opcion_tema": "c",
    "banda_a": "Chayanne",
    "banda_b": "David Bisbal",
    "banda_c": "Enrique Iglesias",
    "opcion_banda": "b",
    "anio_a": "2009",
    "anio_b": "2005",
    "anio_c": "2003",
    "opcion_anio": "a"
  },
  {
    "frase": "Los errores nos eligen, ____",
    "a": "no fallé cuando viniste",
    "b": "para bien o para mal",
    "c": "entre el juego y el azar",
    "respuesta": "b",
    "tema_a": "Adiós",
    "tema_b": "Corazón Partío",
    "tema_c": "Nada Fue Un Error",
    "opcion_tema": "c",
    "banda_a": "Alejandro Sanz",
    "banda_b": "Coti",
    "banda_c": "Juanes",
    "opcion_banda": "b",
    "anio_a": "2002",
    "anio_b": "2008",
    "anio_c": "2019",
    "opcion_anio": "b"
  },
  {
    "frase": "Que cambie por ti, comentaran, __ ___ _______ __ __",
    "a": "que vivo infeliz sin ti",
    "b": "que sigo pendiente de ti",
    "c": "que vivo pendiente de ti",
    "respuesta": "c",
    "tema_a": "El Embrujo",
    "tema_b": "Llorá",
    "tema_c": "Dicen",
    "opcion_tema": "a",
    "banda_a": "Ke Personajes",
    "banda_b": "Los Palmeras",
    "banda_c": "Grupo Red",
    "opcion_banda": "b",
    "anio_a": "2002",
    "anio_b": "2000",
    "anio_c": "2008",
    "opcion_anio": "c"
  },
  {
    "frase": "Un día me amas luego me olvidas, _ _ _ __ ___ lejos de ti",
    "a": "No se si soy feliz",
    "b": "No se si soy debil",
    "c": "No se si estoy feliz",
    "respuesta": "a",
    "tema_a": "No Me Dejes Así",
    "tema_b": "Vienes y te vas",
    "tema_c": "Muero Por Ti",
    "opcion_tema": "B",
    "banda_a": "Marama",
    "banda_b": "Grupo Play",
    "banda_c": "La Base",
    "opcion_banda": "c",
    "anio_a": "2003",
    "anio_b": "2001",
    "anio_c": "1999",
    "opcion_anio": "a"
  },
  {
    "frase": "Y lo mejor que me pudo pasar en el viaje, __ ___ __ ____ _ ____",
    "a": "fue mirar la ventana y seguir",
    "b": "fue mirar el paisaje y seguir",
    "c": "fue mirar tu maldad y seguir",
    "respuesta": "b",
    "tema_a": "Vine hasta aquí",
    "tema_b": "Y lo mejor",
    "tema_c": "En el Viaje",
    "opcion_tema": "a",
    "banda_a": "Las Pastillas del Abuelo",
    "banda_b": "Los Piojos",
    "banda_c": "Ciro y los Persas",
    "opcion_banda": "b",
    "anio_a": "1999",
    "anio_b": "1998",
    "anio_c": "2000",
    "opcion_anio": "c"
  },
  {
    "frase": "si me ven con otra en una disco, ___ ____ ____ ______",
    "a": "solo es perdiendo el tiempo",
    "b": "solo me pongo en riesgo",
    "c": "solo es porque lo siento",
    "respuesta": "a",
    "tema_a": "Voy pa' allá",
    "tema_b": "Ojitos Rojos",
    "tema_c": "un x100to",
    "opcion_tema": "c",
    "banda_a": "Grupo Frontera ft. Bad Bunny",
    "banda_b": "Grupo Frontera ft. Ke Personajes",
    "banda_c": "Fuerza Régida",
    "opcion_banda": "a",
    "anio_a": "2022",
    "anio_b": "2023",
    "anio_c": "2024",
    "opcion_anio": "b"
  },
  {
    "frase": "Ayer que regresé a mi pueblo alguien me dijo que __ __ _______ ",
    "a": "ya te marchaste",
    "b": "ya te bajaste",
    "c": "ya te casaste",
    "respuesta": "c",
    "tema_a": "Hoja en blanco",
    "tema_b": "Sufro",
    "tema_c": "Tu sin Mi",
    "opcion_tema": "a",
    "banda_a": "Nonpalidece",
    "banda_b": "Radagast",
    "banda_c": "Dread Mar I",
    "opcion_banda": "c",
    "anio_a": "2015",
    "anio_b": "2016",
    "anio_c": "2017",
    "opcion_anio": "b"
  },
  {
    "frase": "Inocente me has contado, __ ___ ________",
    "a": "que no llegas a dormir",
    "b": "tu manera de sufrir",
    "c": "como te gusta vivir",
    "respuesta": "b",
    "tema_a": "Inocente",
    "tema_b": "Tu manera de sufrir",
    "tema_c": "Traicionero",
    "opcion_tema": "a",
    "banda_a": "Rombai",
    "banda_b": "La Delio Valdez",
    "banda_c": "Agapornis",
    "opcion_banda": "b",
    "anio_a": "2015",
    "anio_b": "2018",
    "anio_c": "2020",
    "opcion_anio": "b"
  },
  {
    "frase": "Yo sé que la ____ tiene cámaras girando en el espacio",
    "a": "FBI",
    "b": "CIA",
    "c": "NASA",
    "respuesta": "c",
    "tema_a": "Satélite",
    "tema_b": "Espía",
    "tema_c": "NASA",
    "opcion_tema": "c",
    "banda_a": "Camilo & Alejandro Sanz",
    "banda_b": "Camilo",
    "banda_c": "Alejandro Sanz",
    "opcion_banda": "a",
    "anio_a": "2021",
    "anio_b": "2022",
    "anio_c": "2020",
    "opcion_anio": "a"
  },
  {
    "frase": "Por tu culpa me volví un ____",
    "a": "loco",
    "b": "perdedor",
    "c": "bandido",
    "respuesta": "c",
    "tema_a": "Bandido",
    "tema_b": "Loco",
    "tema_c": "Perdedor",
    "opcion_tema": "a",
    "banda_a": "Emanero",
    "banda_b": "Emanero ft. FMK, Estani & Rusherking",
    "banda_c": "Airbag",
    "opcion_banda": "b",
    "anio_a": "2023",
    "anio_b": "2021",
    "anio_c": "2022",
    "opcion_anio": "c"
  },
  {
    "frase": "Ahora enrola y lo prende, _ ____ ___ ____",
    "a": "no se si me miente",
    "b": "es panita del que vende",
    "c": "es amiga del que vende",
    "respuesta": "b",
    "tema_a": "Tranquila",
    "tema_b": "Quietecita",
    "tema_c": "Callaita",
    "opcion_tema": "c",
    "banda_a": "Ozuna",
    "banda_b": "J Balvin",
    "banda_c": "Bad Bunny",
    "opcion_banda": "c",
    "anio_a": "2017",
    "anio_b": "2019",
    "anio_c": "2018",
    "opcion_anio": "b"
  },
  {
    "frase": "Tranquila, Que hoy tu novio acá no va a venir, ______",
    "a": "se acostó a dormir",
    "b": "que yo aprendí bien a compartir ",
    "c": "sabiendo que te tenés que ir",
    "respuesta": "a",
    "tema_a": "Tranquila",
    "tema_b": "Feliz",
    "tema_c": "Suerte",
    "opcion_tema": "a",
    "banda_a": "FMK ft. Maria Becerra",
    "banda_b": "FMK",
    "banda_c": "Maria Becerra",
    "opcion_banda": "a",
    "anio_a": "2023",
    "anio_b": "2021",
    "anio_c": "2022",
    "opcion_anio": "c"
  },
  {
    "frase": "Y Aunque nunca se lo digas, __ ____ __ __ _____",
    "a": "no eres el hombre decente",
    "b": "que no estás solo con ella",
    "c": "Esa mujer se da cuenta",
    "respuesta": "c",
    "tema_a": "La Otra",
    "tema_b": "Con la misma moneda",
    "tema_c": "Jamás",
    "opcion_tema": "c",
    "banda_a": "Cazzu",
    "banda_b": "Dalila",
    "banda_c": "Karina",
    "opcion_banda": "c",
    "anio_a": "2006",
    "anio_b": "2004",
    "anio_c": "2002",
    "opcion_anio": "b"
  },
  {
    "frase": "Yo no necesito vacaciones ni ____ ",
    "a": "dolores de amores",
    "b": "calor de verano",
    "c": "dolores de cabeza",
    "respuesta": "c",
    "tema_a": "Dolor de Cabeza",
    "tema_b": "Vacaciones",
    "tema_c": "Pastillas pa'l dolor",
    "opcion_tema": "b",
    "banda_a": "Wisin",
    "banda_b": "Wisin y Yandel",
    "banda_c": "Yandel",
    "opcion_banda": "a",
    "anio_a": "2015",
    "anio_b": "2017",
    "anio_c": "2018",
    "opcion_anio": "b"
  },
  {
    "frase": "Qué ironía del destino no poder ____",
    "a": "tocarte",
    "b": "besarte",
    "c": "abrazarte",
    "respuesta": "a",
    "tema_a": "Subeme la radio",
    "tema_b": "El Perdón (Remix)",
    "tema_c": "Bailando",
    "opcion_tema": "c",
    "banda_a": "Ricky Martin",
    "banda_b": "Maluma",
    "banda_c": "Enrique Iglesias",
    "opcion_banda": "c",
    "anio_a": "2014",
    "anio_b": "2015",
    "anio_c": "2016",
    "opcion_anio": "a"
  },
  {
    "frase": "Tú me enseñaste que tan simples son las cosas, tú me enseñaste _ __ ____ _ __ ___",
    "a": "a dar amor y nada más",
    "b": "a dar calor y nada más",
    "c": "a dar favor y nada más",
    "respuesta": "a",
    "tema_a": "Guapa",
    "tema_b": "Color Esperanza",
    "tema_c": "Flaca",
    "opcion_tema": "a",
    "banda_a": "Fito Páez",
    "banda_b": "Diego Torres",
    "banda_c": "Luis Miguel",
    "opcion_banda": "b",
    "anio_a": "2004",
    "anio_b": "2001",
    "anio_c": "2010",
    "opcion_anio": "c"
  },
  {
    "frase": "Todo empezó una noche de calor, __ _________ ___ _____ ______",
    "a": "una madrugada de calor",
    "b": "una noche de calor",
    "c": "una tarde de calor",
    "respuesta": "b",
    "tema_a": "Verano de Amor",
    "tema_b": "Amor de Fuego",
    "tema_c": "Amor de Verano",
    "opcion_tema": "c",
    "banda_a": "Estelares",
    "banda_b": "Tan Bionica",
    "banda_c": "Airbag",
    "opcion_banda": "c",
    "anio_a": "2006",
    "anio_b": "2007",
    "anio_c": "2010",
    "opcion_anio": "a"
  },
  {
    "frase": "Cuento con las alas del mar, si no encuentro __ ___ ______ __ ____ _____ _ _____",
    "a": "un ser humano que me quiera llevar",
    "b": "un buen hombre que me pase a buscar",
    "c": "un ser humano que me pase a buscar",
    "respuesta": "c",
    "tema_a": "Mary Poppins y el deshollinador",
    "tema_b": "Sueño que soy yo",
    "tema_c": "Me dicen lo que tengo que hacer",
    "opcion_tema": "a",
    "banda_a": "Adriana Varela",
    "banda_b": "Fabiana Cantilo",
    "banda_c": "Patricia Sosa",
    "opcion_banda": "b",
    "anio_a": "1988",
    "anio_b": "1991",
    "anio_c": "2000",
    "opcion_anio": "b"
  },
  {
    "frase": "No digas nada por favor __ ____ _ __ __ ____",
    "a": "quiero que hablemos de otra cosa",
    "b": "que hablando el alma me destrozas",
    "c": "que bailando el alma me destrozas",
    "respuesta": "a",
    "tema_a": "Yo te esperaré",
    "tema_b": "Para siempre",
    "tema_c": "No digas nada",
    "opcion_tema": "c",
    "banda_a": "Cali y Dandee",
    "banda_b": "Sebastian Yatra",
    "banda_c": "Nicky Jam",
    "opcion_banda": "a",
    "anio_a": "2009",
    "anio_b": "2012",
    "anio_c": "2015",
    "opcion_anio": "b"
  },
  {
    "frase": "Te quise más que al mismo cielo __ __ __ ___ __",
    "a": "Tú eras mía ma'", 
    "b": "y me tiraste por el suelo",
    "c": "Tú eras mi vida ma'",
    "respuesta": "c",
    "tema_a": "Ella Me Levantó",
    "tema_b": "Lo que pasó, pasó",
    "tema_c": "¿Qué tengo que hacer?",
    "opcion_tema": "a",
    "banda_a": "Tito el Bambino",
    "banda_b": "Wisin y Yandel",
    "banda_c": "Daddy Yankee",
    "opcion_banda": "c",
    "anio_a": "2005",
    "anio_b": "2007",
    "anio_c": "2010",
    "opcion_anio": "b"
  },
  {
    "frase": "Por eso, yo te quiero tanto que _ _ __ ____",
    "a": "tu dolor es mi dolor",
    "b": "gracias te doy a ti",
    "c": "no se como explicar",
    "respuesta": "c",
    "tema_a": "Te amo",
    "tema_b": "Para tu amor",
    "tema_c": "Ángel",
    "opcion_tema": "b",
    "banda_a": "Melendi",
    "banda_b": "Ismael Serrano",
    "banda_c": "Juanes",
    "opcion_banda": "c",
    "anio_a": "2004",
    "anio_b": "2006",
    "anio_c": "2008",
    "opcion_anio": "a"
  },
  {
    "frase": "Amor ____, amor de contrabando",
    "a": "mío",
    "b": "pirata",
    "c": "loco",
    "respuesta": "b",
    "tema_a": "Amor Pirata",
    "tema_b": "Amor de Locura",
    "tema_c": "Contrabando de Amor",
    "opcion_tema": "a",
    "banda_a": "Los Nocheros",
    "banda_b": "Los Manseros Santiagueños",
    "banda_c": "Grupo Uno",
    "opcion_banda": "c",
    "anio_a": "2005",
    "anio_b": "2002",
    "anio_c": "2010",
    "opcion_anio": "b"
  },
  {
    "frase": "No hay brillo en las estrellas, ya _ _ _ __",
    "a": "ni el sol me calienta",
    "b": "ni el sol me contesta",
    "c": "no está a mi lado",
    "respuesta": "a",
    "tema_a": "Digale",
    "tema_b": "Estás Muy Bien",
    "tema_c": "No Me Expliquen",
    "opcion_tema": "a",
    "banda_a": "Axel",
    "banda_b": "David Villa",
    "banda_c": "David Bisbal",
    "opcion_banda": "c",
    "anio_a": "2000",
    "anio_b": "2002",
    "anio_c": "2005",
    "opcion_anio": "b"
  },
  {
    "frase": "Me gustaría poderte bañar, También, secarte _ ___ __ ____",
    "a": "y volverte a bañar",
    "b": "y volverte a enjuagar",
    "c": "porque me gustas mucho",
    "respuesta": "b",
    "tema_a": "Cuando Lloras",
    "tema_b": "Lejos",
    "tema_c": "Me Gustas Mucho",
    "opcion_tema": "c",
    "banda_a": "Damas Gratis",
    "banda_b": "Nene Malo",
    "banda_c": "Viejas Locas",
    "opcion_banda": "c",
    "anio_a": "1998",
    "anio_b": "1999",
    "anio_c": "2002",
    "opcion_anio": "b"
  },
  {
    "frase": "Él no te entrega nada, en cambio __ __ ___ __ __",
    "a": "yo te ofrezco mi tiempo",
    "b": "yo te ofrezco mi amor",
    "c": "yo te ofrezco mi vida",
    "respuesta": "c",
    "tema_a": "Qué Ironía",
    "tema_b": "Ocho Cuarenta",
    "tema_c": "Ya no te quiere",
    "opcion_tema": "a",
    "banda_a": "Tru-la-lá",
    "banda_b": "Sabroso",
    "banda_c": "Rodrigo",
    "opcion_banda": "c",
    "anio_a": "1995",
    "anio_b": "1999",
    "anio_c": "2000",
    "opcion_anio": "b"
  },
  {
    "frase": "Y de nuevo en ese cuarto se desnudan piel a piel. Se desgarran y se entregan __ __ __ _ _ ____",
    "a": "a la cama y al placer",
    "b": "a las ganas y al placer",
    "c": "él con su mujer",
    "respuesta": "b",
    "tema_a": "Ocho Cuarenta",
    "tema_b": "Lo mejor del amor",
    "tema_c": "Lo que he vivido contigo",
    "opcion_tema": "b",
    "banda_a": "Rodrigo",
    "banda_b": "Alejandro Lerner",
    "banda_c": "Walter Olmos",
    "opcion_banda": "a",
    "anio_a": "1996",
    "anio_b": "2012",
    "anio_c": "2010",
    "opcion_anio": "a"
  },
  {
    "frase": "Si nos dejan nos vamos a ____",
    "a": "vivir un gran amor",
    "b": "amar hasta morir",
    "c": "querer toda la vida",
    "respuesta": "c",
    "tema_a": "Si Nos Dejan",
    "tema_b": "Toda la Vida",
    "tema_c": "Gran Amor",
    "opcion_tema": "a",
    "banda_a": "Luis Miguel",
    "banda_b": "José Alfredo Jiménez",
    "banda_c": "Javier Solís",
    "opcion_banda": "a",
    "anio_a": "1999",
    "anio_b": "1995",
    "anio_c": "2000",
    "opcion_anio": "b"
  },
  {
    "frase": "No es lo mismo un beso de vago, que _ __ _ _ __",
    "a": "que los celos de ese tontito",
    "b": "porque sabe que estamos al ritmo",
    "c": "y aunque yo soy un calavera",
    "respuesta": "a",
    "tema_a": "Abajo del foquito",
    "tema_b": "Beso de Vago",
    "tema_c": "Amor de Vago",
    "opcion_tema": "c",
    "banda_a": "La T y La M ft. Malandro de América",
    "banda_b": "La T y La M ft. Ecko",
    "banda_c": "La T y La M ft Uriel Lozano",
    "opcion_banda": "a",
    "anio_a": "2022",
    "anio_b": "2024",
    "anio_c": "2025",
    "opcion_anio": "b"
  },
  {
    "frase": "Si te sientes aburrida y hasta un poco __",
    "a": "frígida",
    "b": "despavorida",
    "c": "deprimida",
    "respuesta": "c",
    "tema_a": "Amores Eternos",
    "tema_b": "Tan Sólo Amantes",
    "tema_c": "Hay Amores Que Nunca Se Olvidan",
    "opcion_tema": "b",
    "banda_a": "Sergio Denis",
    "banda_b": "Leo Mattioli",
    "banda_c": "Rodrigo",
    "opcion_banda": "b",
    "anio_a": "2004",
    "anio_b": "1999",
    "anio_c": "1995",
    "opcion_anio": "a"
  },
  {
    "frase": "Yo no soy marinero, soy ____",
    "a": "timonel",
    "b": "pirata",
    "c": "capitán",
    "respuesta": "c",
    "tema_a": "La Bamba",
    "tema_b": "Soy Capitán",
    "tema_c": "Marinero No Soy",
    "opcion_tema": "a",
    "banda_a": "Tradicional",
    "banda_b": "Los Lobos",
    "banda_c": "Ritchie Valens",
    "opcion_banda": "c",
    "anio_a": "1958",
    "anio_b": "1940",
    "anio_c": "1987",
    "opcion_anio": "a"
  },
  {
    "frase": "Pero yo no soy tu prisionero. Y no tengo alma _ __",
    "a": "de doctor",
    "b": "de robot",
    "c": "de color",
    "respuesta": "b",
    "tema_a": "Corazón",
    "tema_b": "Prisionero",
    "tema_c": "Alma",
    "opcion_tema": "a",
    "banda_a": "Catupecumachu",
    "banda_b": "Los Auténticos Decadentes",
    "banda_c": "Los del Fuego",
    "opcion_banda": "b",
    "anio_a": "1990",
    "anio_b": "1992",
    "anio_c": "1995",
    "opcion_anio": "c"
  },
  {
    "frase": "__ las manos si quieres fumanchar, __ las manos",
    "a": "alza",
    "b": "arriba",
    "c": "levanta",
    "respuesta": "a",
    "tema_a": "Levanta las manos",
    "tema_b": "Alza las manos",
    "tema_c": "Arriba las manos",
    "opcion_tema": "b",
    "banda_a": "Pibes Chorros",
    "banda_b": "Damas Gratis",
    "banda_c": "Néstor en Bloque",
    "opcion_banda": "b",
    "anio_a": "2000",
    "anio_b": "1999",
    "anio_c": "2004",
    "opcion_anio": "c"
  },
  {
    "frase": "Te diré solo adios no se cuánto hacía que _ __ _",
    "a": "no estaba él",
    "b": "no te quería ver",
    "c": "no estaba bien",
    "respuesta": "c",
    "tema_a": "Auto Rojo",
    "tema_b": "Mojada",
    "tema_c": "Bye, bye",
    "opcion_tema": "c",
    "banda_a": "La Mosca",
    "banda_b": "Los Caligaris",
    "banda_c": "Vilma Palma e Vampiros",
    "opcion_banda": "c",
    "anio_a": "2001",
    "anio_b": "1989",
    "anio_c": "1991",
    "opcion_anio": "c"
  },
  {
    "frase": "El mal de ojo que me manden me lo quito. Yo no soy y ni voy a ser _ ___",
    "a": "tu caramelito",
    "b": "tu bizcochito",
    "c": "tu delito",
    "respuesta": "b",
    "tema_a": "Bizcochito",
    "tema_b": "Caramelito",
    "tema_c": "Delito",
    "opcion_tema": "a",
    "banda_a": "Nathy Peluso",
    "banda_b": "Rosalía",
    "banda_c": "Cazzu",
    "opcion_banda": "b",
    "anio_a": "2020",
    "anio_b": "2022",
    "anio_c": "2025",
    "opcion_anio": "b"
  },
  {
    "frase": "Yo tan solo quiero ser _ __ __ __ __",
    "a": "tu tregua cada mañana",
    "b": "las 4 patas de tu cama",
    "c": "tu carnaval, tus principios y tus finales",
    "respuesta": "b",
    "tema_a": "Tregua",
    "tema_b": "Tu Jardín con Enanitos",
    "tema_c": "Enanitos",
    "opcion_tema": "b",
    "banda_a": "Melendi",
    "banda_b": "Juanes",
    "banda_c": "David Bisbal",
    "opcion_banda": "a",
    "anio_a": "2025",
    "anio_b": "2012",
    "anio_c": "2005",
    "opcion_anio": "b"
  },
  {
    "frase": "Dile que yo estoy muy bien,  ____",
    "a": "Que nunca he estado solo",
    "b": "Que nunca he estado peor",
    "c": "Que nunca he estado mejor",
    "respuesta": "c",
    "tema_a": "Si la ven",
    "tema_b": "Dile",
    "tema_c": "Si la ves",
    "opcion_tema": "c",
    "banda_a": "Sin Bandera",
    "banda_b": "Franco de Vita",
    "banda_c": "Romeo Santos",
    "opcion_banda": "b",
    "anio_a": "1995",
    "anio_b": "2004",
    "anio_c": "2025",
    "opcion_anio": "b"
  },
  {
    "frase": "Tengo una fe que madura. Que va conmigo y me cura. Desde que te _",
    "a": "vi",
    "b": "conocí",
    "c": "mentí",
    "respuesta": "b",
    "tema_a": "Hoy",
    "tema_b": "Voy a verte de nuevo",
    "tema_c": "Hoy voy a verte de nuevo",
    "opcion_tema": "a",
    "banda_a": "Emilia",
    "banda_b": "Rosana",
    "banda_c": "Gloria Stefan",
    "opcion_banda": "c",
    "anio_a": "1990",
    "anio_b": "1995",
    "anio_c": "2003",
    "opcion_anio": "c"
  },
  {
    "frase": "Te pintaron ___ en el aire",
    "a": "pajaritos",
    "b": "colibríes",
    "c": "gorrioncitos",
    "respuesta": "a",
    "tema_a": "Te pintaron gorrioncitos",
    "tema_b": "Te pintaron colibríes",
    "tema_c": "Te pintaron pajaritos",
    "opcion_tema": "c",
    "banda_a": "Wisin y Yandel",
    "banda_b": "Nene Malo",
    "banda_c": "Andy Rivera y Yandar & Yostin",
    "opcion_banda": "c",
    "anio_a": "2010",
    "anio_b": "2012",
    "anio_c": "2015",
    "opcion_anio": "b"
  },
  {
    "frase": "Qué bien se ve. Me hipnotiza su cintura. Cuando baila ________",
    "a": "hasta los dioses la quieren ver",
    "b": "todos los hombres la quieren ver",
    "c": "hasta los hombres la quieren ver",
    "respuesta": "a",
    "tema_a": "Reggaetón Lento (Bailemos)",
    "tema_b": "Bailemos",
    "tema_c": "Reggaetón",
    "opcion_tema": "a",
    "banda_a": "Danny Ocean",
    "banda_b": "Wisin y Yandel",
    "banda_c": "C'NCO",
    "opcion_banda": "c",
    "anio_a": "2015",
    "anio_b": "2016",
    "anio_c": "2017",
    "opcion_anio": "b"
  },
  {
    "frase": "Me gusta _____, me gustas tú. Me gusta ____, me gustas tú",
    "a": "marihuana / ecuatoriana",
    "b": "marihuana / colombiana",
    "c": "mañana / mexicana",
    "respuesta": "b",
    "tema_a": "Nadie Más",
    "tema_b": "Me Gustas Tú",
    "tema_c": "Solamente Tú",
    "opcion_tema": "b",
    "banda_a": "Ricardo Arjona",
    "banda_b": "Pablo Alborán",
    "banda_c": "Manu Chao",
    "opcion_banda": "c",
    "anio_a": "2001",
    "anio_b": "2011",
    "anio_c": "2005",
    "opcion_anio": "a"
  },
  {
    "frase": "Como la flor, con tanto ____",
    "a": "pasión",
    "b": "dolor",
    "c": "amor",
    "respuesta": "c",
    "tema_a": "Bidi Bidi Bom Bom",
    "tema_b": "Como la Flor",
    "tema_c": "Amor Prohibido",
    "opcion_tema": "b",
    "banda_a": "Selena",
    "banda_b": "Soda Stereo",
    "banda_c": "Carlos Vives",
    "opcion_banda": "a",
    "anio_a": "1994",
    "anio_b": "1994",
    "anio_c": "1992",
    "opcion_anio": "c"
  },
  {
    "frase": "Se me ha perdido un corazón, si alguien lo tiene, por favor, _ _ __",
    "a": "que lo devuelva",
    "b": "que me lo tenga",
    "c": "que lo detenga",
    "respuesta": "a",
    "tema_a": "Se me ha perdido un corazon",
    "tema_b": "Se Me Perdió",
    "tema_c": "Un Corazón Perdido",
    "opcion_tema": "c",
    "banda_a": "Gilda",
    "banda_b": "Dalila",
    "banda_c": "Selena",
    "opcion_banda": "a",
    "anio_a": "1995",
    "anio_b": "1993",
    "anio_c": "1997",
    "opcion_anio": "c"
  },
  {
    "frase": "Y no me pueden parar Me levanté del piso y _ _ __ __",
    "a": "ya no quiero penar",
    "b": "ya quiero bailar",
    "c": "ya no quiero llorar",
    "respuesta": "c",
    "tema_a": "Me Levanté",
    "tema_b": "Perdedor",
    "tema_c": "Soñador",
    "opcion_tema": "a",
    "banda_a": "Leo Mattioli",
    "banda_b": "Rodrigo",
    "banda_c": "Ulises Bueno",
    "opcion_banda": "c",
    "anio_a": "2022",
    "anio_b": "2000",
    "anio_c": "2005",
    "opcion_anio": "a"
  },
  {
    "frase": "Vuela una lagrima Porque  ____",
    "a": "le duele la soledad",
    "b": "no estás aquí",
    "c": "quiere estar cerca de tí",
    "respuesta": "b",
    "tema_a": "Vuela una Lagrima",
    "tema_b": "Lágrimas",
    "tema_c": "Vuela",
    "opcion_tema": "a",
    "banda_a": "Los Nocheros",
    "banda_b": "Sergio Denis",
    "banda_c": "Leo Mattioli",
    "opcion_banda": "a",
    "anio_a": "2001",
    "anio_b": "1990",
    "anio_c": "2003",
    "opcion_anio": "a"
  },
  {
    "frase": "Yo solo quiero que la gente cante Por todos lados esta canción, ___ ____ __ ______",
    "a": "Desde San Juan hasta Barranquilla",
    "b": "Desde San Luis  hasta Barranquilla",
    "c": "De Santa Marta hasta Barranquilla",
    "respuesta": "a",
    "tema_a": "Subeme la radio",
    "tema_b": "Quiero sonar en la radio",
    "tema_c": "Mi primer millón",
    "opcion_tema": "c",
    "banda_a": "La Secta All Star",
    "banda_b": "Maná",
    "banda_c": "Bacilos",
    "opcion_banda": "c",
    "anio_a": "2000",
    "anio_b": "2002",
    "anio_c": "2005",
    "opcion_anio": "b"
  },
  {
    "frase": "El amor de mi vida sigue siendo ____",
    "a": "él",
    "b": "ella",
    "c": "tú",
    "respuesta": "c",
    "tema_a": "El Amor de Mi Vida",
    "tema_b": "Sigue Siendo Tú",
    "tema_c": "Ella",
    "opcion_tema": "a",
    "banda_a": "Camilo Sesto",
    "banda_b": "Dyango",
    "banda_c": "Raphael",
    "opcion_banda": "a",
    "anio_a": "1968",
    "anio_b": "1978",
    "anio_c": "1988",
    "opcion_anio": "b"
  },
  {
    "frase": "Solo una pobre canción __ __ _ mi guitarra",
    "a": "da vueltas por",
    "b": "se cae por",
    "c": "se desgarra por",
    "respuesta": "a",
    "tema_a": "Zamba para vos",
    "tema_b": "Zamba para no morir",
    "tema_c": "Zamba para olvidarte",
    "opcion_tema": "c",
    "banda_a": "Los Nocheros",
    "banda_b": "Daniel Toro",
    "banda_c": "Los Carabajal",
    "opcion_banda": "b",
    "anio_a": "1976",
    "anio_b": "1995",
    "anio_c": "1998",
    "opcion_anio": "a"
  },
  {
    "frase": "¿Cómo __ ___ va a ser rey del pop?, ey, con ___ y ____",
    "a": "Bad Bunny / reggaeton y dembow",
    "b": "Daddy / reggaeton y dembow",
    "c": "Chencho / reggaeton y dembow",
    "respuesta": "a",
    "tema_a": "Nueva York",
    "tema_b": "Si TE Quieres divertir",
    "tema_c": "NUEVAYoL",
    "opcion_tema": "c",
    "banda_a": "Daddy Yankee",
    "banda_b": "Chencho Corleone",
    "banda_c": "Bad Bunny",
    "opcion_banda": "c",
    "anio_a": "2025",
    "anio_b": "2022",
    "anio_c": "2020",
    "opcion_anio": "a"
  },
  {
    "frase": "Loca, vos no entendés nada de vivir, Se fueron con _____ tus ganas de mí",
    "a": "septiembre",
    "b": "noviembre",
    "c": "diciembre",
    "respuesta": "a",
    "tema_a": "Me Gustás Loca",
    "tema_b": "Loca",
    "tema_c": "Loca de atar",
    "opcion_tema": "b",
    "banda_a": "Tan Bionica",
    "banda_b": "Chano",
    "banda_c": "Bambi",
    "opcion_banda": "a",
    "anio_a": "2008",
    "anio_b": "2009",
    "anio_c": "2010",
    "opcion_anio": "c"
  },
  {
    "frase": "Ay, mi corazón. Está en estado de __. Se chocó con la __",
    "a": "gravedad / verdad",
    "b": "verdad / gravedad",
    "c": "gravedad / realidad",
    "respuesta": "c",
    "tema_a": "Mi Corazón",
    "tema_b": "Gravedad",
    "tema_c": "Corazón",
    "opcion_tema": "a",
    "banda_a": "Tiago PZK",
    "banda_b": "FMK",
    "banda_c": "Rusherking",
    "opcion_banda": "a",
    "anio_a": "2020",
    "anio_b": "2022",
    "anio_c": "2024",
    "opcion_anio": "c"
  },
  {
    "frase": "Voy a quemar la ___ de tu ____",
    "a": "yerba  / locura",
    "b": "piedra / locura",
    "c": "yerba  / cordura ",
    "respuesta": "b",
    "tema_a": "Fasolita querido",
    "tema_b": "Verano del 95",
    "tema_c": "Verano del 92",
    "opcion_tema": "c",
    "banda_a": "Los Piojos",
    "banda_b": "Bersuit Vergarabat",
    "banda_c": "Ciro y Los Persas",
    "opcion_banda": "a",
    "anio_a": "1990",
    "anio_b": "1992",
    "anio_c": "1996",
    "opcion_anio": "c"
  },
  {
    "frase": "Fueron más ___ para volverte a ver, Y así sos vos, y así soy yo. Somos tan distintos, mujer",
    "a": "mentiras",
    "b": "horas",
    "c": "lugares",
    "respuesta": "a",
    "tema_a": "Y así soy yo",
    "tema_b": "Tan Distintos",
    "tema_c": "Y así sos vos",
    "opcion_tema": "b",
    "banda_a": "La Mancha de Rolando",
    "banda_b": "Guasones",
    "banda_c": "Estelares",
    "opcion_banda": "b",
    "anio_a": "2014",
    "anio_b": "2016",
    "anio_c": "2018",
    "opcion_anio": "a"
  },
   {
    "frase": "'El lujo es _____' dijo y me _____",
    "a": "verdad / conquistó",
    "b": "vulgaridad / flechó",
    "c": "vulgadirad / conquistó",
    "respuesta": "c",
    "tema_a": "Una tipa rapaz",
    "tema_b": "Ji Ji Ji",
    "tema_c": "Un poco de amor francés",
    "opcion_tema": "c",
    "banda_a": "Patricio Rey y sus Redonditos de Ricota",
    "banda_b": "Los Redondos",
    "banda_c": "La Renga",
    "opcion_banda": "a",
    "anio_a": "1991",
    "anio_b": "1986",
    "anio_c": "1989",
    "opcion_anio": "a"
  },
  {
    "frase": "Vivo like boss 'Toy cocinando Holly con tu hoe La puse a ___ y ella no cree en __",
    "a": "orar  / Dios",
    "b": "rezar / vos",
    "c": "rezar / Dios",
    "respuesta": "c",
    "tema_a": "Like Boss",
    "tema_b": "Vivo Like Boss",
    "tema_c": "Cocinando Holly",
    "opcion_tema": "a",
    "banda_a": "YSY A",
    "banda_b": "Frijo",
    "banda_c": "Duki",
    "opcion_banda": "b",
    "anio_a": "2019",
    "anio_b": "2020",
    "anio_c": "2022",
    "opcion_anio": "a"
  },
  {
    "frase": "A ella le gusta la gasolina (____)",
    "a": "qué le den gasolina",
    "b": "dame más gasolina",
    "c": "como le encanta la gasolina",
    "respuesta": "b",
    "tema_a": "Gasolina",
    "tema_b": "Lo Que Pasó, Pasó",
    "tema_c": "Pobre Diabla",
    "opcion_tema": "a",
    "banda_a": "Daddy Yankee",
    "banda_b": "Wisin & Yandel",
    "banda_c": "Don Omar",
    "opcion_banda": "a",
    "anio_a": "2003",
    "anio_b": "2004",
    "anio_c": "2005",
    "opcion_anio": "b"
  },
  {
    "frase": "Me puse la' Gucci con un short de Nike, buzo y cadena, ____",
    "a": "me siento violento",
    "b": "estoy que exploto",
    "c": "estoy que goteo",
    "respuesta": "c",
    "tema_a": "Rockstar",
    "tema_b": "She Don't Give a FO",
    "tema_c": "Goteo",
    "opcion_tema": "c",
    "banda_a": "Duki",
    "banda_b": "Duki & C.R.O",
    "banda_c": "Khea & Duki",
    "opcion_banda": "a",
    "anio_a": "2019",
    "anio_b": "2020",
    "anio_c": "2018",
    "opcion_anio": "a"
  },
  {
    "frase": "Ya no ____, no quiero lastimarme de vuelta",
    "a": "vuelvas",
    "b": "llames",
    "c": "busques",
    "respuesta": "a",
    "tema_a": "Pobre Corazón",
    "tema_b": "Un Finde",
    "tema_c": "Ya No Vuelvas",
    "opcion_tema": "c",
    "banda_a": "La K'onga, Luck Ra & Ke Personajes",
    "banda_b": "Big One & Ke Personajes",
    "banda_c": "Ivy Queen",
    "opcion_banda": "a",
    "anio_a": "2023",
    "anio_b": "2023",
    "anio_c": "2004",
    "opcion_anio": "a"
  },
  {
    "frase": "Hay una ____ sola, se está moviendo, quiere un cuartetazo violento",
    "a": "rubia",
    "b": "morocha",
    "c": "pelirroja",
    "respuesta": "b",
    "tema_a": "La Pelirroja",
    "tema_b": "La Rubia",
    "tema_c": "La Morocha",
    "opcion_tema": "c",
    "banda_a": "Luck Ra ft. BM",
    "banda_b": "La Mona Jiménez",
    "banda_c": "Dalila",
    "opcion_banda": "a",
    "anio_a": "2008",
    "anio_b": "2024",
    "anio_c": "2005",
    "opcion_anio": "b"
  },
  {
    "frase": "Tírame una ____ que se vea, en la nave mientra' hacemos cosa' feas",
    "a": "foto",
    "b": "selfie",
    "c": "mirada",
    "respuesta": "a",
    "tema_a": "Una Foto Remix",
    "tema_b": "Además de Mí",
    "tema_c": "Sin Pijama",
    "opcion_tema": "a",
    "banda_a": "Becky G & Natti Natasha",
    "banda_b": "Rauw & Nicki",
    "banda_c": "Mesita, Emilia, Nicki Nicole & Tiago PZK",
    "opcion_banda": "c",
    "anio_a": "2018",
    "anio_b": "2021",
    "anio_c": "2023",
    "opcion_anio": "c"
  },
  {
    "frase": "Pero cuando se apaga la ____ se siente bien portarse mal",
    "a": "TV",
    "b": "música",
    "c": "luz",
    "respuesta": "a",
    "tema_a": "Mi Cuarto",
    "tema_b": "Jet Lag",
    "tema_c": "La_Original.mp3",
    "opcion_tema": "c",
    "banda_a": "Emilia ft. Tini",
    "banda_b": "Tini",
    "banda_c": "Emilia & Duki",
    "opcion_banda": "a",
    "anio_a": "2023",
    "anio_b": "2022",
    "anio_c": "2024",
    "opcion_anio": "c"
  },
  {
    "frase": "Mi mujer me estaba llamando, pero yo no ____",
    "a": "contesté",
    "b": "escuché",
    "c": "miré",
    "respuesta": "a",
    "tema_a": "Te Boté",
    "tema_b": "China",
    "tema_c": "Con Calma",
    "opcion_tema": "b",
    "banda_a": "Anuel AA, Daddy Yankee, Karol G, Ozuna & J Balvin",
    "banda_b": "Casper, Nio García, Darell",
    "banda_c": "Daddy Yankee",
    "opcion_banda": "a",
    "anio_a": "2019",
    "anio_b": "2018",
    "anio_c": "2019",
    "opcion_anio": "c"
  },
  {
    "frase": "Antes tú me pichaba', ahora yo ____",
    "a": "picheo",
    "b": "te picho",
    "c": "me pichas",
    "respuesta": "a",
    "tema_a": "Safaera",
    "tema_b": "Callaita",
    "tema_c": "Yo Perreo Sola",
    "opcion_tema": "c",
    "banda_a": "Los Auténticos Decadentes",
    "banda_b": "Bad Bunny",
    "banda_c": "Bad Bunny ft. Jowell & Randy",
    "opcion_banda": "b",
    "anio_a": "2020",
    "anio_b": "2020",
    "anio_c": "2019",
    "opcion_anio": "a"
  },
  {
    "frase": "Llegué al club con el combo, rápido la vi ____",
    "a": "cerca",
    "b": "lejos",
    "c": "bailando",
    "respuesta": "b",
    "tema_a": "Nos Fuimos en Una",
    "tema_b": "Quevedo: Bzrp Music Sessions #52",
    "tema_c": "Quédate",
    "opcion_tema": "b",
    "banda_a": "Grupo Frontera & Bad Bunny",
    "banda_b": "Feid & Bizarrap",
    "banda_c": "Bizarrap & Quevedo",
    "opcion_banda": "c",
    "anio_a": "2023",
    "anio_b": "2022",
    "anio_c": "2023",
    "opcion_anio": "b"
  },
  {
    "frase": "Hola ____, soy yo el ex amor de tu vida",
    "a": "perdida",
    "b": "loca",
    "c": "mentirosa",
    "respuesta": "a",
    "tema_a": "Hola Perdida",
    "tema_b": "Hola Remix",
    "tema_c": "Ya Me Enteré",
    "opcion_tema": "a",
    "banda_a": "Luck Ra ft. Khea",
    "banda_b": "Luck Ra & Tini",
    "banda_c": "Reik ft. Ozuna",
    "opcion_banda": "a",
    "anio_a": "2016",
    "anio_b": "2023",
    "anio_c": "2024",
    "opcion_anio": "c"
  },
  {
    "frase": "Éramos tan buenos amigos ____, que yo probé tu desempeño en el amor",
    "a": "desde siempre",
    "b": "ayer",
    "c": "hasta hoy",
    "respuesta": "c",
    "tema_a": "Perfecta",
    "tema_b": "Don",
    "tema_c": "Yo No Sé",
    "opcion_tema": "a",
    "banda_a": "Bandana",
    "banda_b": "Miranda!",
    "banda_c": "Mambrú",
    "opcion_banda": "b",
    "anio_a": "2005",
    "anio_b": "2007",
    "anio_c": "2002",
    "opcion_anio": "b"
  },
  {
    "frase": "Todas las mañanas que viví, todas las calles donde me ____",
    "a": "perdí",
    "b": "escondí",
    "c": "encontré",
    "respuesta": "b",
    "tema_a": "Mariposa Tecknicolor",
    "tema_b": "11 y 6",
    "tema_c": "Al Lado del Camino",
    "opcion_tema": "a",
    "banda_a": "Divididos",
    "banda_b": "Fito Páez",
    "banda_c": "La Renga",
    "opcion_banda": "b",
    "anio_a": "1994",
    "anio_b": "1990",
    "anio_c": "1998",
    "opcion_anio": "a"
  },
  {
    "frase": "Despacito, quiero respirar tu cuello ____",
    "a": "despacito",
    "b": "lentamente",
    "c": "suavemente",
    "respuesta": "a",
    "tema_a": "Despacito",
    "tema_b": "Échame La Culpa",
    "tema_c": "Felices los 4",
    "opcion_tema": "a",
    "banda_a": "Luis Fonsi ft. Daddy Yankee",
    "banda_b": "Luis Fonsi & Demi Lovato",
    "banda_c": "Maluma",
    "opcion_banda": "a",
    "anio_a": "2017",
    "anio_b": "2018",
    "anio_c": "2015",
    "opcion_anio": "a"
  },
  {
    "frase": "Con calma, yo quiero ver cómo ella lo ____",
    "a": "mueve",
    "b": "baila",
    "c": "menea",
    "respuesta": "c",
    "tema_a": "Con Calma",
    "tema_b": "Dura",
    "tema_c": "Tusa",
    "opcion_tema": "a",
    "banda_a": "Daddy Yankee",
    "banda_b": "Karol G & Nicki Minaj",
    "banda_c": "Daddy Yankee ft. Snow",
    "opcion_banda": "c",
    "anio_a": "2019",
    "anio_b": "2020",
    "anio_c": "2018",
    "opcion_anio": "a"
  },
  {
    "frase": "Y yo le di un ____ en la boca, pa' cada loco su loca",
    "a": "cachetazo",
    "b": "mordisco",
    "c": "besito",
    "respuesta": "c",
    "tema_a": "Mujeriego",
    "tema_b": "Loca",
    "tema_c": "¿Y Pa' La Wacha Loca? Remix",
    "opcion_tema": "c",
    "banda_a": "Gusty DJ, La Joaqui, L-Gante & Salastkbron",
    "banda_b": "La Joaqui",
    "banda_c": "Damas Gratis",
    "opcion_banda": "a",
    "anio_a": "2008",
    "anio_b": "2021",
    "anio_c": "2023",
    "opcion_anio": "c"
  },
  {
    "frase": "Te prefiero ____, inalcanzable",
    "a": "fuera de foco",
    "b": "lejos de mí",
    "c": "en mis sueños",
    "respuesta": "a",
    "tema_a": "Signos",
    "tema_b": "Persiana Americana",
    "tema_c": "Nada Personal",
    "opcion_tema": "b",
    "banda_a": "Daddy Yankee",
    "banda_b": "Soda Stereo",
    "banda_c": "Divididos",
    "opcion_banda": "b",
    "anio_a": "1986",
    "anio_b": "1987",
    "anio_c": "1988",
    "opcion_anio": "a"
  },
  {
    "frase": "Yo caminaré entre las piedras hasta sentir el ____",
    "a": "temblor en mis piernas",
    "b": "calor del sol",
    "c": "frío de la noche",
    "respuesta": "a",
    "tema_a": "Cuando Pase el Temblor",
    "tema_b": "Prófugos",
    "tema_c": "En El Séptimo Día",
    "opcion_tema": "a",
    "banda_a": "Bersuit",
    "banda_b": "Soda Stereo",
    "banda_c": "Carlos Vives",
    "opcion_banda": "b",
    "anio_a": "1989",
    "anio_b": "1985",
    "anio_c": "1986",
    "opcion_anio": "b"
  },
  {
    "frase": "Y que me ____ todo y no tenga nada",
    "a": "falte",
    "b": "sobre",
    "c": "quite",
    "respuesta": "a",
    "tema_a": "Hola Perdida",
    "tema_b": "Ya No Vuelvas",
    "tema_c": "Que Me Falte Todo",
    "opcion_tema": "c",
    "banda_a": "Luck Ra ft. Khea",
    "banda_b": "La K'onga & Luck Ra",
    "banda_c": "Luck Ra ft. Abel Pintos",
    "opcion_banda": "c",
    "anio_a": "2024",
    "anio_b": "2023",
    "anio_c": "2024",
    "opcion_anio": "a"
  },
  {
    "frase": "Shaky shaky shaky shaky ____",
    "a": "¿Cómo es? ",
    "b": "¿Qué fue? ",
    "c": "¿Qué es?",
    "respuesta": "a",
    "tema_a": "Shaky",
    "tema_b": "Shaky Shaky",
    "tema_c": "Shaky Shaky Shaky",
    "opcion_tema": "c",
    "banda_a": "Yandel",
    "banda_b": "Feid",
    "banda_c": "Daddy Yankee",
    "opcion_banda": "c",
    "anio_a": "2015",
    "anio_b": "2022",
    "anio_c": "2017",
    "opcion_anio": "c"
  },
  {
    "frase": "Pude haber sido yo La que tiene tu __ ___",
    "a": "corazón guardado",
    "b": "corazon marchitado",
    "c": "pobre corazón",
    "respuesta": "a",
    "tema_a": "Consejo de amor",
    "tema_b": "Porqué te vas",
    "tema_c": "Pobre Corazón",
    "opcion_tema": "a",
    "banda_a": "Tini ft. Cali y Dandee",
    "banda_b": "Tini ft. Morat",
    "banda_c": "Tini ft. Tiago PZK",
    "opcion_banda": "b",
    "anio_a": "2018",
    "anio_b": "2020",
    "anio_c": "2023",
    "opcion_anio": "a"
  },
  {
    "frase": "Diablo, qué ____, tú tiene' un culo cabrón",
    "a": "locura",
    "b": "bellaquera",
    "c": "safaera",
    "respuesta": "c",
    "tema_a": "Dákiti",
    "tema_b": "Yo Perreo Sola",
    "tema_c": "Safaera",
    "opcion_tema": "c",
    "banda_a": "Bad Bunny",
    "banda_b": "Bad Bunny & Jhay Cortez",
    "banda_c": "Bad Bunny ft. Jowell & Randy y Ñengo Flow",
    "opcion_banda": "c",
    "anio_a": "2020",
    "anio_b": "2022",
    "anio_c": "2024",
    "opcion_anio": "a"
  },
  {
    "frase": "Vámonos ____ de aquí, ay papi dime que sí",
    "a": "solos",
    "b": "juntos",
    "c": "lejos",
    "respuesta": "c",
    "tema_a": "El Amor de Mi Vida",
    "tema_b": "La Curiosidad",
    "tema_c": "Otra Noche en Miami",
    "opcion_tema": "a",
    "banda_a": "Los Ángeles Azules ft. Emilia",
    "banda_b": "Los Ángeles Azules ft. Nicki Nicole",
    "banda_c": "Los Ángeles Azules ft. Maria Becerra",
    "opcion_banda": "c",
    "anio_a": "2024",
    "anio_b": "2020",
    "anio_c": "2021",
    "opcion_anio": "a"
  },
  {
    "frase": "Y ahora todo está ____, antes cuando te quería tú no me querías ver",
    "a": "de cabeza",
    "b": "al derecho",
    "c": "al revés",
    "respuesta": "c",
    "tema_a": "Al Revés",
    "tema_b": "Nena",
    "tema_c": "Mala Mía",
    "opcion_tema": "a",
    "banda_a": "Lali",
    "banda_b": "Emilia",
    "banda_c": "Cazzu",
    "opcion_banda": "c",
    "anio_a": "2018",
    "anio_b": "2020",
    "anio_c": "2019",
    "opcion_anio": "c"
  },
  {
    "frase": "Ojalá que los mío' nunca se __ Y si hoy me __, pues que me ayuden",
    "a": "mueran / emborracho",
    "b": "muden  / quiebro",
    "c": "muden  / emborracho",
    "respuesta": "c",
    "tema_a": "nUevaYOL",
    "tema_b": "DtMF",
    "tema_c": "DeBÍ TiRAR MáS FOToS",
    "opcion_tema": "b",
    "banda_a": "Bad Bunny",
    "banda_b": "Daddy Yankee",
    "banda_c": "Don Omar",
    "opcion_banda": "a",
    "anio_a": "2020",
    "anio_b": "2024",
    "anio_c": "2025",
    "opcion_anio": "c"
  }]
  